- name: install latest qemu-guest-agent
  hosts: "*"
  tasks:
    - name: install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
      become: true
    - name: Make sure qemu-guest-agent is started
      systemd:
        name: qemu-guest-agent.service
        state: started
      become: true
