  hosts: "*"
  become: true
  tasks:
      name: apt update and upgrade Ubuntu
      apt:
        update_cache: yes
        upgrade: 'yes'

      name: install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true

      name: Make sure qemu-guest-agent is started
      systemd:
        name: qemu-guest-agent.service
        state: start

      name: install zsh on all hosts
      apt:
        name: zsh
        state: present
        update_cache: true

      name: set timezone
      shell: timedatectl set-timezone America/New_York

      name: stop timesyncd
      systemd:
      name: systemd-timesyncd.service
      state: stopped

      name: Copy over the timesyncd config
      template: src=/home/tbrocato/Intuos-Corp/kubauto/ansible/templates/timesyncd.conf dest=/etc/systemd/timesyncd.conf

      name: Make sure timesyncd is started
      systemd:
      name: systemd-timesyncd.service
      state: started
